version: 2.1

parameters:
  branch_to_track:
    type: string
    default: "circleci"
  s3_bucket:
    type: string
    default: "uzky-circleci-bucket"

jobs:
  build:
    # branches:
    #   only: 
    #     - << pipeline.parameters.branch-to-track >>
    
    working_directory: ~/store-webapp-sample

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      # - run:

      ###
      # - run:
      #     name: Generate cumulative pom.xml checksum
      #     command: |
      #       find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
      #       sort -o ~/pom-checksum ~/pom-checksum.tmp
      #     when: always

      - restore_cache:
          key: store-webapp-sample-{{ checksum "~/pom" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: store-webapp-sample-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/store-webapp.jar

      - run:
          name: Prepare for s3 placement
          command: |
            sudo apt-get update -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt install zip -y

      - run:
          name: Send build to s3
          command: |
            aws configure set aws_access_key_id $CIRCLECI_FIRST_AWS_AKID
            aws configure set aws_secret_access_key $CIRCLECI_FIRST_AWS_SAK

            cd target/
            zip store-webapp.jar.zip store-webapp.jar
            aws s3 cp store-webapp.jar.zip s3://<< pipeline.parameters.s3_bucket >>/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - << pipeline.parameters.branch_to_track >>