version: 2.1

parameters:
  branch_to_track:
    type: string
    default: "circleci"
  build_name:
    type: string
    default: "store-webapp"
  s3_bucket:
    type: string
    default: "uzky-circleci-bucket"

jobs:
  build:
    working_directory: ~/store-webapp-sample

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: store-webapp-sample-{{ checksum "pom.xml" }}
      
      - run: 
          name: Get project dependencies
          command: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: store-webapp-sample-{{ checksum "pom.xml" }}
      
      - run: 
          name: Make project build
          command: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/<< pipeline.parameters.build_name >>.jar

      - run:
          name: Prepare for AWS S3 placement
          command: |
            sudo apt-get update -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt install zip -y

      - run:
          name: Send build to AWS S3
          command: |
            aws configure set aws_access_key_id $CIRCLECI_FIRST_AWS_AKID
            aws configure set aws_secret_access_key $CIRCLECI_FIRST_AWS_SAK

            cd target/
            dt=$(date "+%d%m%Y%H%M%S")
            zip "<< pipeline.parameters.build_name >>$dt.jar.zip" << pipeline.parameters.build_name >>.jar
            aws s3 cp "<< pipeline.parameters.build_name >>$dt.jar.zip" s3://<< pipeline.parameters.s3_bucket >>/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - << pipeline.parameters.branch_to_track >>